language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4" 
before_install:
  - npm install -g npm@4.5.0
before_script:
  - npm install
script: npm test && npm run functionaltest