sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "8.0.0"
  - "7"
  - "6"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"

jobs:
  include:
    - stage: "Application Insights Node.js SDK Tests (Extended Metrics Library not installed)"
      name: "Application Insights Node.js SDK Tests"
      before_install:
        - npm install -g npm@4.5.0
      script:
        - npm test
        # Run funcs for current release
        - if [ "$TRAVIS_NODE_VERSION" = "12" ]; then npm run functionaltest; fi
        # Run funcs for LTS releases (currently 6, 8, 10)
        - if [ "$TRAVIS_NODE_VERSION" = "10" ]; then npm run functionaltest; fi
        - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then npm run functionaltest; fi
        - if [ "$TRAVIS_NODE_VERSION" = "6" ]; then npm run functionaltest; fi
        - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then npm run functionaltest; fi
        # latest node8 uses cls-hooked for dependency correlation, while 8.0.0 uses
        # plain cls instead, so run funcs for 8.0.0 as well
        - if [ "$TRAVIS_NODE_VERSION" = "8.0.0" ]; then npm run functionaltest; fi

        # Only run backcompat tests once
        - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then npm run backcompattest; fi
    - stage: "Application Insights Extended Node.js Metrics Tests (Extended Metrics Library installed"
      name: "Application Insights Extended Node.js Metrics Tests"
      before_install:
        - npm install -g npm@4.5.0
        # Simulate optionalDevDependency for applicationinsights-native-metrics
        - npm uninstall applicationinsights-native-metrics --save-dev
        - npm install applicationinsights-native-metrics --save-optional || true
      script:
        - npm test
        # Run funcs for current release
        - if [ "$TRAVIS_NODE_VERSION" = "12" ]; then npm run functionaltest; fi
        # Run funcs for LTS releases (currently 6, 8, 10)
        - if [ "$TRAVIS_NODE_VERSION" = "10" ]; then npm run functionaltest; fi
        - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then npm run functionaltest; fi
