sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
  - "9"
  - "8"
  - "7"
  - "6"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4" 
before_install:
  - npm install -g npm@4.5.0
before_script:
  - npm install
script:
  - npm test
  # Only run funcs for LTS releases
  - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "6" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then npm run functionaltest; fi
  # Only run backcompat tests once
  - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then npm run backcompattest; fi