sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
  - "11"
  - "10"
  - "9"
  - "8"
  - "8.2.1"
  - "8.2.0"
  - "8.1.3"
  - "8.1.0"
  - "8.0.0"
  - "7"
  - "6"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4" 
before_install:
  - npm install -g npm@4.5.0
before_script:
  - npm install
script:
  - npm test
  # Only run funcs for LTS releases
  - if [ "$TRAVIS_NODE_VERSION" = "11" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "10" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "9" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "8.2.1" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "8.2.0" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "8.1.3" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "8.1.0" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "8.0.0" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "7" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "6" ]; then npm run functionaltest; fi
  - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then npm run functionaltest; fi
  # Only run backcompat tests once
  - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then npm run backcompattest; fi